services:
    - type: web
    name: handwriting-backend
    env: python
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

    - type: web
    name: handwriting-frontend
    env: node
    region: singapore
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run serve -- --port $PORT --host 0.0.0.0
